spring.application.name=shardedsagawallet


# ? Hibernate / JPA Configuration

spring.jpa.hibernate.ddl-auto=none
# ? Automatically creates database tables each time app starts
# Options you can use:
#   create = drop + create tables every start (for dev)
#   update = auto-update schema (good for testing)
#   none / validate = production-safe

spring.jpa.show-sql=true
# ? Shows SQL queries in console ? helpful for debugging what Hibernate executes

spring.jpa.properties.hibernate.format_sql=true
# ? Formats SQL output nicely in logs (adds indentation/newlines)

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# ? Tells Hibernate that it should generate SQL compatible with MySQL

# ------------------------------
# ? ShardingSphere DataSource Configuration
# ------------------------------

spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yml
# ? Main point of integration!
# This tells Spring to use the ShardingSphere JDBC driver
# and load sharding rules from the YAML file located at:
#   src/main/resources/sharding.yml
# The YAML contains multiple data sources + sharding logic.

spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
# ? ShardingSphere?s custom JDBC driver
# It sits **between your app and actual databases**.
# Internally, it:
#   1. Reads your sharding.yml
#   2. Opens multiple DB connections
#   3. Routes SQL queries automatically to correct shard




#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#spring.datasource.url=jdbc:shardingsphere:classPath:sharding.yml
#spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver