spring.application.name=shardedsagawallet

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:shardingsphere:classPath:sharding.yml
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver

# JWT Config
jwt.secret=5b4c3a2e1f0d9e8c7b6a594837261504f3e2d1c0b9a8796857463524314049382716051
# minimum 32 characters hona chahiye
jwt.expiration=86400000
# 86400000 ms = 24 hours